---
title: "Schisto Optimal Control"

author:  |
  | Christopher M. Hoover $^1$, Carl Boettiger $^2$, Justin Remais $^1$ 
  | $^1$UC Berkeley EHS, $^2$UC Berkeley ESPM
  
abstract: |
  Abstract goes here...

# bibliography: 
# csl:
  
output: word_document
fig_caption: yes

header-includes:
  - \usepackage{endfloat}    
  - \usepackage{setspace}\doublespacing
  - \usepackage{lineno}
  - \linenumbers
---

```{r setup, include=FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE)

knitr::opts_chunk$set(fig.pos = 'p') # Places figures on their own pages
knitr::opts_chunk$set(out.width = '100%', dpi=300)

require(adaptivetau)
require(deSolve)
require(tidyverse)
```

### Potential titles  
* From control to elimination of schistosomiasis: insights from helminth biology and optimal control theory  
* Optimal control of schistosomiasis in the presence of diagnostic and epidemiologic uncertainty

# Introduction  
* Development as a driver of infectious disease control and elimination
  * Current strategies to control infectious diseases of poverty/Neglected tropical diseases do not attempt to complement or take advantage of development
* Current global strategy for schistosomiasis control and elimination relies on mass drug administration (MDA), which is plagued by reinfection  
* Reliance on MDA based on quick reductions in morbidity, but does not consider DALYs accumulated over long time periods
* Control and elimination strategies that complement development by considering longterm goals of elimination may be more effective in reducing cumulative burden over medium to long tim horizons  
* Optimal control theory/stochastic dynamic programming used to explore optimal strategies in managed systems with uncertainty

# Methods and analysis  
## Data  
### Cost of interventions  
* [Lo et al PNAS](http://www.pnas.org/content/early/2018/01/03/1708729114) 

### Development rates  

## Models  
### SDP framework  
* Objective is to minimize the cost/DALY averted with cost measured in USD and DALYs estimated from models implementing interventions and simulated through time  
* State variable *W*, the mean worm burden in the human population, is affected by interventions and used to estimate DALYs averted  
* Decision variable is where/when to where to commit capital to interventions. I.e. which interventions and at what time (esp. considering seasonal transmission)
* Transition model

## Analysis  
*

# Results  

# Discussion  